### ISSUE TITLE
[ProxyFilePath] Remove dependency to $SOCIALCUBEPATH/statistics/ folder

### ISSUE THREAD

**Issue by mbamba** [SocialSim/SocialCube#5]
Support absolute paths inside the proxy config file and remain independent from the $SOCIALCUBEPATH/statistics folder

This would allow running socialcube from any directory, providing an absolute path to the proxy file and absolute paths to the statistics files.

It would also be helpful to print out which statistics files are being looked for and opened. Currently, there is only an assert() but no mention of which file was not located.

**Comment by leowangx2013** [comment]
Hi Mouna,
I just pushed a commit. Now we can use absolute/relative path to specify the proxy file and statistic files.

For example, if the proxy file is under the root directory of SocialCube, to run the simulation, we can first access the _src_ directory, and use the command like:

`./socialcube --show_profile --show_event -s 2017-07-01T00:00:00Z -e 2017-08-31T23:59:59Z --proxy_config_file ../ProxyFilePaths_simple.config`

and the content of _ProxyFilePaths_simple.config_ is:

```
#SimpleBehavior
userIDProxyFile=../statistics/data_05_24/data_simple_july_august/all_userIDs-2017-06.csv
hourlyActionRateFile=../statistics/data_05_24/data_simple_july_august/user_action_rate.csv
objectPreferenceProxyFile=../statistics/data_05_24/data_simple_july_august/user_object_preference.json
typeDistributionProxyFile=../statistics/data_05_24/data_simple_july_august/user_type_distribution.csv
```

Here I use relative path to specify the files. Since the current directory is __src/__ , so I use __..__ to go back to the upper level directory.

Besides, now I print out the paths of the proxy files that are used in the simulation.  For example:

```
StatisticProxy-25-parseUserID:
userIDProxyFile: ../statistics/data_05_24/data_simple_july_august/all_userIDs-2017-06.csv
UserIDProxy-27-parse:                               User ID has 1574238
StatisticProxy-43-parseHourlyActionRate:
hourlyActionRateProxyFile: ../statistics/data_05_24/data_simple_july_august/user_action_rate.csv
HourlyActionRateProxy-42-parse:                     Hourly Action Rate has 1574238
StatisticProxy-37-parseObjectPreference:
objectPreferenceProxyFile: ../statistics/data_05_24/data_simple_july_august/user_object_preference.json
ObjectPreferenceProxy-40-parse:                     Object Preference has 1574238
StatisticProxy-49-parseTypeDistribution:
typeDistributionProxyFile: ../statistics/data_05_24/data_simple_july_august/user_type_distribution.csv
TypeDistributionProxy-38-parse:                     Type Distribution Rate has 1574238
```

Thanks
